[project]
authors = ["horned_axe <horned_axe@proton.me>"]
channels = ["nvidia/label/cuda-12.4.0","nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "CTR-GCN"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12"
setuptools = "*"
cuda = { version = "*", channel = "nvidia/label/cuda-12.4.0" }
pytorch = { version = "*", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
pytorch-cuda = { version = "12.4", channel = "pytorch" }
pyyaml = "*"
tqdm = "*"
tensorboardX = "*"
scikit-learn = "*"
h5py = "*"
matplotlib = "*"
networkx = "*"
einops = ">=0.8.1,<0.9"
timm = ">=1.0.14,<2"

[pypi-dependencies]
torchlight = {path = "./torchlight"}
