# feeder
feeder: feeders.feeder_ucla_dual.FeederDual  # 修改为新的供料器
train_feeder_args:
  data_path: data/NW-UCLA/all_sqe_edge  # 边特征数据路径
  label_path: train
  debug: False
  repeat: 5
  normalization: False
  embed_dim: 64

test_feeder_args:
  data_path: data/NW-UCLA/all_sqe_edge
  label_path: val
  debug: False
  normalization: False
  embed_dim: 64

# model
model: model.lglt.LGLT
model_args:
  num_class: 10
  num_frames: 200
  num_edges: 19  # UCLA数据集的边数，线图的节点数
  in_channels: 3
  embed_dim: 64
  num_layers: 4
  num_heads: 32
  mlp_ratio: 4.0
  qkv_bias: True
  drop_rate: 0.1
  attn_drop_rate: 0.1
  drop_path_rate: 0.1

# optim
weight_decay: 0.0001
base_lr: 0.1
lr_decay_rate: 0.1
step: [50]

# training
device: 0
batch_size: 32
test_batch_size: 64
num_epoch: 65
nesterov: True
warm_up_epoch: 5