# feeder
feeder: feeders.feeder_ucla_dual.FeederDual
train_feeder_args:
  data_path: data/NW-UCLA/all_sqe_edge
  label_path: train
  debug: False
  repeat: 5
  normalization: False
  embed_dim: 64

test_feeder_args:
  data_path: data/NW-UCLA/all_sqe_edge
  label_path: val
  debug: False
  normalization: False
  embed_dim: 64

# model
model: model.transformer_classifier.TransformerTimeSeries
model_args:
  num_class: 10
  num_frames: 200
  num_edges: 19  # UCLA数据集的边数
  in_channels: 3
  d_model: 64
  nhead: 8
  num_layers: 4
  dim_feedforward: 256
  dropout: 0.1
  activation: 'gelu'
  use_cls_token: True
  pool_mode: 'cls'  # 'cls', 'mean' 或 'attention'

# optim
weight_decay: 0.0001
base_lr: 0.1
lr_decay_rate: 0.1
step: [50]

# training
device: 0
batch_size: 32
test_batch_size: 64
num_epoch: 65
nesterov: True
warm_up_epoch: 5